### ISSUE TITLE
products

### ISSUE THREAD

**Issue by jszafran** [jszafran/w84it#10]
- [x] create model
- [x]  add product view
- [x] edit product view
- [x] delete product view
- [x] follow product feature
- [x] unit tests

**Comment by jszafran** [comment]
@MattBlack85 
Product model includes price - how do you handle currencies in your apps? Implementing them by yourself or using any external libraries?

**Comment by MattBlack85** [comment]
It really depends on the use, is the only thing you have to deal with is a float and nothing else then go for decimalfield
